<?php

namespace ApplicationBundle\Repository;

/**
 * EtudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtudesRepository extends \Doctrine\ORM\EntityRepository
{
}
