<?php

namespace ApplicationBundle\Repository;

/**
 * SituationProRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituationProRepository extends \Doctrine\ORM\EntityRepository
{
}
