services:
#    application.example:
#        class: ApplicationBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

services:
    application.test_user:
        class: ApplicationBundle\TestUser\TestUser
        arguments: ['@service_container']
